#!/usr/bin/env bash
# Sxript that configures a new Ubuntu machine to requirements

sudo apt-get update
sudo apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
