#!/usr/bin/env bash
# Bash script containing commands to automatically configure a Ubuntu machine

sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
new_string="server_name_;\n\trewrite ^\/redirect_me https:\/\/https://www.youtube.com/watch?v=E1T8XWx8Q2c;"
sudo sed -i "server_name;/$new_string/" /etc/nginx/sites-enabled/default

sudo service nginx restart
