#!/usr/bin/env bash
# Make a custom 404

sudo apt-get update
sudo apt-get install -y nginx

# code to redirect a specific endpoint
echo "Hello World!" | sudo tee /var/www/html/index.html
new_string="server_name_;\n\trewrite ^\/redirect_me https:\/\/https://www.youtube.com/watch?v=E1T8XWx8Q2c;"
sudo sed -i "s/server_name_;/$new_string/" /etc/nginx/sites-enabled/default

# code to create error page and add a redirect for error 404
echo " Ceci n'est pas une page" | sudo tee /var/www/html/index.html
new_string="listen 80 default_server;\n\terrot_page 404 \/404.html;\n\tlocation = \/400.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

sudo service nginx restart
