#!/usr/bin/env bash
# install a configure HAproxy on your lb-01 server

sudo apt-get update
sudo apt-get install -y haproxy

#set up the balance loader
server_config=\
"
frontend alxhttp
	bind *:80
	mode http
	default_backend alx-back

backend alx-back
	balance roundrobin
	server 427615-web-01 54.237.86.2:80 check
	server 427615-web-02 52.86.58.243:80 check
	mode http
"

echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable the haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart

