#!/usr/bin/env bash
# Configure a specific ip to firwall rules

sudo apt update
sude apt-get install ufw
sudo ufw enable

sudo ufw default deny incoming

sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

sudo ufw status verbose
